# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                                                                       
language: python                                                                                                                                                                                         
                                                                                                                                                                                                         
# Versão que a aplicação suporta.                                                                                                                                                                        
python:                                                                                                                                                                                                  
  - "3.7.9"                                                                                                                                                                                              

os: "linux"
dist: "xenial"

jobs:
    include:
        - stage: Testes

          name: "Testes Unitários"
          # Instalação de Módulos que são necessários para a Aplicação.
          install:
            - pip install flask flask-wtf coverage

          # Defini o script de Teste que deve rodar toda vez que o código for alterado.
          script:
            - coverage run test.py || travis_terminate 1;
            - coverage report app.py || travis_terminate 1;
            - coverage xml app.py || travis_terminate 1;


        - script:
            - sonar-scanner || travis_terminate 1;

          name: "Testes de Qualidade e Segurança"
          addons:
              sonarcloud:
                  organization: andersoncab
                  token: ${SONAR_TOKEN}


        - stage: Deploy

          script: skip

          # Definir o Deploy no Heroku
          deploy:
              provider: heroku
              strategy: api
              api_key: $HEROKU_API_KEY
              edge: true
              app: devopslab-anderson
              on:
                  branch: main

# slack
# notifications:
    #  slack: 
    #  on_success: always
    #  on_failure: always
